apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations: # Enable prometheus scrape
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "{{ .Values.PORT }}"
    spec: # Pod spec
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.PORT }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "100m"    # 100 milli cores
          limits:
            memory: "128Mi" # 128 mebibytes 
            cpu: "100m"
