apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
data:
  PORT: "{{ .Values.PORT }}"
  MAX_SIZE: "{{ .Values.MAX_SIZE }}"
